export const GET_CITIES = 'GET_CITIES' 
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR' 

export const GET_ITINERARIES = 'GET_ITINERARIES' 
export const GET_ITINERARIES_ERROR = 'GET_ITINERARIES_ERROR' 
